Add new configure option --with-mixedrefs for mixed pointer mode
ibmruntimes/openj9-openjdk-jdk8 pull request #458
Opened 2020-11-12 19:57 UTC by sharon-wang

JDK8 port of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/359.

2020-11-12 20:20 UTC, sharon-wang commented
FYI @keithc-ca @gacholio

2020-11-12 22:35 UTC, keithc-ca requested changes

2020-11-12 22:35 UTC, keithc-ca commented on jdk/make/closed/autoconf/generated-configure.sh
> +DATE_WHEN_GENERATED=1605209646
Please include corresponding changes to `jdk/make/closed/autoconf/generated-configure.sh`.

2020-11-12 23:50 UTC, sharon-wang commented
The `generated-configure.sh` file automatically removed `runstatedir`-related code. Is this supposed to happen?

2020-11-13 01:15 UTC, keithc-ca commented
> The `generated-configure.sh` file automatically removed `runstatedir`-related code. Is this supposed to happen?

That's a sign that you're using a slightly older version of autoconf (even though it might report it's version 2.69). The one in Ubuntu 18.04 or newer won't do that.

2020-11-13 03:04 UTC, sharon-wang commented
Yes, I was building on OSX and it was reporting v2.69 for autoconf. I've run the autogen script again on Ubuntu 20.04 -- `runstatedir`-related code is now un-removed.

2020-11-13 20:35 UTC, keithc-ca commented
Jenkins compile aix,osx,win,win32,zlinux jdk8

2020-11-13 23:51 UTC, keithc-ca approved these changes

2020-11-13 23:51 UTC, merged