Add CRIU enablement flags for jdk8
ibmruntimes/openj9-openjdk-jdk8 pull request #508
Opened 2021-06-10 19:13 UTC by tajila

Add CRIU enablement flags for jdk8

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

2021-06-10 19:13 UTC, tajila commented
@keithc-ca Please review these changes

2021-06-10 20:00 UTC, keithc-ca requested changes

2021-06-10 20:00 UTC, keithc-ca commented on closed/OpenJ9.gmk
> +
No trailing whitespace, please.

2021-06-10 20:00 UTC, keithc-ca commented on jdk/make/closed/autoconf/custom-hook.m4
> +AC_DEFUN([OPENJ9_CONFIGURE_CRIU_SUPPORT],
In jdk8, changes to configuration files such as this require re-running `bash common/autoconf/autogen.sh`.

2021-06-11 20:14 UTC, tajila commented
@keithc-ca changes are ready for another look

2021-06-11 20:36 UTC, keithc-ca commented
Jenkins compile ppc64le_linux_uma,win32 jdk8

2021-06-11 21:37 UTC, keithc-ca approved these changes

2021-06-11 21:37 UTC, merged