FIPS Support for Linux x86 RHEL
ibmruntimes/openj9-openjdk-jdk8 pull request #590
Opened 2022-07-18 20:46 UTC by WilburZjh

Signed-off-by: Jinhang Zhang <Jinhang.Zhang@ibm.com>

2022-07-18 23:06 UTC, keithc-ca requested changes

2022-07-18 23:06 UTC, keithc-ca commented on jdk/make/CopyFiles.gmk
> +  NSS_FIPS_CFG_SRC := $(TOPDIR)/closed/src/java.base/share/conf/security/nss.fips.cfg
This path is wrong, it should be:
```
  NSS_FIPS_CFG_SRC := $(TOPDIR)/closed/adds/jdk/src/share/conf/security/nss.fips.cfg
```

2022-07-19 14:16 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/ec/SunEC.java
> +
There are no engines (Key Factory engine, Algorithm Parameter engine, Signature engines, Key Pair Generator engine, etc) listed in SunEC in JDK8 like JDK11/JDK17. I just removed the `import` statement, and keep this `SunEC.java` file not changing.

2022-07-19 14:18 UTC, WilburZjh commented on jdk/make/CopyFiles.gmk
> +  NSS_FIPS_CFG_DST := $(CONF_DST_DIR)/security/nss.fips.cfg
Edited.

2022-07-19 14:18 UTC, WilburZjh commented on closed/adds/jdk/src/share/classes/openj9/internal/security/FIPSConfigurator.java
> +                new PrivilegedAction<>() {
Edited.

2022-07-19 14:18 UTC, WilburZjh commented on jdk/src/share/classes/java/security/SecureRandom.java
> +            prngService = p.getService("SecureRandom", prng);
Edited.

2022-07-19 14:19 UTC, WilburZjh commented on jdk/src/share/classes/java/security/SecureRandom.java
> +        String prng = null;
Edited.

2022-07-19 14:19 UTC, WilburZjh commented on jdk/make/CopyFiles.gmk
> +  NSS_FIPS_CFG_SRC := $(TOPDIR)/closed/src/java.base/share/conf/security/nss.fips.cfg
Edited.

2022-07-19 16:41 UTC, keithc-ca commented on jdk/src/share/classes/java/security/SecureRandom.java
> +        String prng = null;
This has not been addressed.

2022-07-19 17:51 UTC, WilburZjh commented on jdk/src/share/classes/java/security/SecureRandom.java
> +        String prng = null;
Fixed.

2022-07-19 21:17 UTC, WilburZjh commented on closed/make/CopyFiles.gmk
> +################################################################################
removed.

2022-08-11 15:53 UTC, WilburZjh commented
@keithc-ca @pshipton Please let me know if there are any other changes need to be made.

2022-08-11 17:11 UTC, keithc-ca approved these changes
These changes look reasonable to me, but I'll let @pshipton move this out of draft mode assuming he agrees it's time to do so.

2022-08-11 17:15 UTC, alon-sh commented
we are looking to have FIPS mode support for jdk8 for the next release - therefore we need to merge this PR to have Lan enable testing for jdk8 so we can get started on the testing aspect of the work. 

FYI @mstoodle

2022-08-15 14:48 UTC, pshipton approved these changes

2022-08-15 14:48 UTC, merged

2022-08-15 18:54 UTC, pshipton commented
This doesn't actually work so I'm going to revert it and a new PR can be created.

2022-08-15 19:03 UTC, pshipton commented
Some review comments are:
- in jdk8 the java.security file is in ${java.home}/lib/security (not conf)
- the java.security specifies the full package names of the providers, i.e.
```
security.provider.1=sun.security.provider.Sun
security.provider.2=sun.security.rsa.SunRsaSign
security.provider.3=sun.security.ec.SunEC
security.provider.4=com.sun.net.ssl.internal.ssl.Provider
security.provider.5=com.sun.crypto.provider.SunJCE
```

2022-08-16 19:38 UTC, WilburZjh commented
Issues fixed in #601