PKCS#12 file-based Keystore support for FIPS mode
ibmruntimes/openj9-openjdk-jdk8 pull request #673
Opened 2023-06-08 16:45 UTC by WilburZjh

This is a backport PR from JDKNext PR https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/573 & https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/606 to JDK8.

2023-06-12 21:13 UTC, WilburZjh commented
Hi @keithc-ca , please help to review.

2023-06-13 18:53 UTC, keithc-ca requested changes

2023-06-13 20:25 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/P11Key.java
> + * (c) Copyright IBM Corp. 2023, 2023 All Rights Reserved
Updated.

2023-06-13 20:25 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/SunPKCS11.java
> + * (c) Copyright IBM Corp. 2023, 2023 All Rights Reserved
Updated.

2023-06-13 20:25 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/wrapper/PKCS11.java
> + * (c) Copyright IBM Corp. 2023, 2023 All Rights Reserved
Updated.

2023-06-13 20:25 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/P11Key.java
> +import sun.security.util.ECUtil;
Removed.

2023-06-13 20:25 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/SunPKCS11.java
> +import java.math.BigInteger;
Updated.

2023-06-13 20:25 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/SunPKCS11.java
> -import java.security.InvalidKeyException;
So you want me to add them back?

2023-06-13 20:25 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/SunPKCS11.java
> +import sun.security.rsa.RSAUtil.KeyType;
Updated.

2023-06-14 13:06 UTC, keithc-ca requested changes

2023-06-14 13:57 UTC, WilburZjh commented on jdk/src/share/classes/sun/security/pkcs11/SunPKCS11.java
> +import sun.security.rsa.RSAPrivateCrtKeyImpl;
Reversed.

2023-06-14 16:54 UTC, keithc-ca approved these changes

2023-06-14 16:54 UTC, merged