Optimize AES/GCM cipher and IV initialization and improve array cleanup code
ibmruntimes/openj9-openjdk-jdk8 pull request #690
Opened 2023-09-11 18:45 UTC by KostasTsiounis

The cipher initialization cost has been found to be computationally expensive, especially in the OpenSSL 3.x API.

In order to optimize the cost of using OpenSSL to perform consecutive AES/GCM encryption and decryption operations, two flags are set and passed as parameters.

The first flag indicates whether a different cipher is required for the upcoming operations (i.e., the key size has changed). If that is the case, a cipher is initialized and set to the provided context. If not, those steps are omitted, thus reducing the time required for the operation.

The second flag indicates whether the IV length has changed and is used in a similar way as the first flag.

The rest of the steps required for the operation are performed regardless of the flags.

The handling of freeing arrays that were part of that functionality is, also, updated to comply with the newer approach to cleanup code.

Back-ported from: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/655

Signed-off by: Kostas Tsiounis <kostas.tsiounis@ibm.com>

2023-09-12 17:20 UTC, keithc-ca requested changes

2023-09-12 17:22 UTC, KostasTsiounis commented on closed/adds/jdk/src/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java
> +    private static final byte[] EMPTY_BUF = new byte[0];
Changed.

2023-09-12 18:50 UTC, keithc-ca commented
Jenkins test sanity win jdk8

2023-09-13 13:12 UTC, keithc-ca commented
Additional testing in https://openj9-jenkins.osuosl.org/job/Grinder/2887 passed.

2023-09-13 13:13 UTC, keithc-ca approved these changes

2023-09-13 13:13 UTC, merged