Add additional checks to NativeECDHKeyAgreement to match upstream
ibmruntimes/openj9-openjdk-jdk8 pull request #754
Opened 2024-05-15 14:14 UTC by KostasTsiounis

There are additional checks that are required during the `init` and `doPhase` parts of `ECDH` key agreement. Those checks are already present in the original `ECDHKeyAgreement` class, so they had to be added to the `NativeECDHKeyAgreement` class as well.

Back-ported from: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/788

Signed-off by: Kostas Tsiounis [kostas.tsiounis@ibm.com](mailto:kostas.tsiounis@ibm.com)

2024-05-15 14:33 UTC, KostasTsiounis commented
FYI @keithc-ca

2024-05-23 21:34 UTC, keithc-ca requested changes

2024-05-23 21:34 UTC, keithc-ca commented on closed/adds/jdk/src/share/classes/sun/security/ec/NativeECDHKeyAgreement.java
> +import java.util.Optional;
Please remove this unused import.

2024-05-23 21:34 UTC, keithc-ca commented on closed/adds/jdk/src/share/classes/sun/security/ec/NativeECDHKeyAgreement.java
> +
Please remove this unused field.

2024-05-24 13:53 UTC, KostasTsiounis commented on closed/adds/jdk/src/share/classes/sun/security/ec/NativeECDHKeyAgreement.java
> +import java.util.Optional;
Removed.

2024-05-24 13:54 UTC, KostasTsiounis commented on closed/adds/jdk/src/share/classes/sun/security/ec/NativeECDHKeyAgreement.java
> +
Removed.

2024-05-24 14:45 UTC, keithc-ca commented
Jenkins test sanity alinux jdk8

2024-05-24 17:50 UTC, KostasTsiounis commented
The `TestEC` one is a known issue (see https://github.com/eclipse-openj9/openj9/issues/19479). I have the fix for that and you should see a PR soon.

The other one doesn't seem `ECDH` related. Maybe we should open another issue for that.

2024-05-27 13:38 UTC, keithc-ca commented
Grinder for jdk_security3 passed in https://openj9-jenkins.osuosl.org/job/Grinder/3628 (running on the same machine as used by https://openj9-jenkins.osuosl.org/job/Grinder/3627).

2024-05-27 13:38 UTC, keithc-ca approved these changes

2024-05-27 13:38 UTC, merged