Fix configure support for RAM class persistence
ibmruntimes/openj9-openjdk-jdk8 pull request #773
Opened 2024-10-28 20:38 UTC by ThanHenderson

Signed-off-by: Nathan Henderson <nathan.henderson@ibm.com>

2024-10-28 20:43 UTC, ThanHenderson commented
@keithc-ca please continue the review of https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/770 here.

2024-10-29 14:40 UTC, ThanHenderson commented
I'll add the correct handling of the UMA flag here; I am now adding it appropriately on the OpenJ9 side.

2024-10-29 18:30 UTC, keithc-ca requested changes

2024-10-29 18:30 UTC, keithc-ca commented on closed/OpenJ9.gmk
>  endif # OPENJ9_ENABLE_SNAPSHOTS
Like with other flags, this should not make assumptions about the default:
```
ifeq (true,$(OPENJ9_ENABLE_SNAPSHOTS))
  FEATURE_SED_SCRIPT += $(call SedEnable,opt_snapshots)
else # OPENJ9_ENABLE_SNAPSHOTS
  FEATURE_SED_SCRIPT += $(call SedDisable,opt_snapshots)
endif # OPENJ9_ENABLE_SNAPSHOTS
```

2024-10-31 00:25 UTC, keithc-ca commented
Unless there's a good reason not to, equivalent changes should be proposed for
* https://github.com/ibmruntimes/openj9-openjdk-jdk
* https://github.com/ibmruntimes/openj9-openjdk-jdk23
* https://github.com/ibmruntimes/openj9-openjdk-jdk21
* https://github.com/ibmruntimes/openj9-openjdk-jdk17
* https://github.com/ibmruntimes/openj9-openjdk-jdk11

2024-10-31 00:31 UTC, keithc-ca commented
Jenkins compile zlinux jdk8

2024-10-31 12:48 UTC, keithc-ca approved these changes

2024-10-31 12:48 UTC, merged

2024-10-31 13:23 UTC, ThanHenderson commented
> Unless there's a good reason not to, equivalent changes should be proposed for

I don't see a reason why we shouldn't do this. I'll open those today.

2024-10-31 17:43 UTC, ThanHenderson commented
@keithc-ca I've opened:
next: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/873
23: https://github.com/ibmruntimes/openj9-openjdk-jdk23/pull/66
21: https://github.com/ibmruntimes/openj9-openjdk-jdk21/pull/217
17: https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/404
11: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/833